AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  MyWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pirlog-simon-cloud-website
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  CloudResumeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloudresume-test
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      DeletionProtectionEnabled: false

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getViews
      Runtime: python3.9
      Role: arn:aws:iam::010438510855:role/service-role/getViews-role-gkcufb3f
      Handler: lambda_function.lambda_handler
      Description: ""
      Timeout: 3
      MemorySize: 128
      TracingConfig:
        Mode: PassThrough
      PackageType: Zip
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      SnapStart:
        ApplyOn: None
        OptimizationStatus: Off
      RuntimeVersionConfig:
        RuntimeVersionArn: arn:aws:lambda:eu-west-1::runtime:be9e7121d3264b1e86158b38dbbb656c23dff979eb481793ee37b9e2b79fda22
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/getViews
      CodeUri: ./path/to/your/code

  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: pirlog-simon-cloud-website.s3-website-eu-west-1.amazonaws.com
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
            QueryString: false
        Origins:
          - DomainName: pirlog-simon-cloud-website.s3-website-eu-west-1.amazonaws.com
            Id: pirlog-simon-cloud-website.s3-website-eu-west-1.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:010438510855:certificate/0a397c4c-e6d1-4f74-adbc-fb09c848ccaa
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - simondevops.online
          - www.simondevops.online

  MyRoute53Record:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: Z086652426I94UVQSUO5N # Your hosted zone ID
      RecordSets:
        - Name: simondevops.online # Your domain name
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID (do not change)
            DNSName: !GetAtt MyDistribution.DomainName

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::pirlog-simon-cloud-website/*"
